### ISSUE TITLE
Update : How ?

### ISSUE THREAD

**Issue by gamersalpha** [YunoHost-Apps/discourse_ynh#6]
Hello there i have this message can u explain how update please  ??

![image](https://user-images.githubusercontent.com/32466950/48706008-2e3f0200-ebfb-11e8-8c65-bd77df482d51.png)

thanks to u

**Comment by JimboJoe** [comment]
Hello,
The way this YunoHost package is designed, the upgrade will be provided by a YunoHost package update.
It hasn't been done so far as there are some touchy adaptations to make (Discourse 2.1.x won't build as-is on a YunoHost target), which I haven't had enough free time yet to tackle.

**Comment by Josue-T** [comment]
> It hasn't been done so far as there are some touchy adaptations to make (Discourse 2.1.x won't build as-is on a YunoHost target), which I haven't had enough free time yet to tackle.

@JimboJoe, could you give some more information about that. Maybe I could help if you have some more informations.

**Comment by JimboJoe** [comment]
Hey, thanks for your help!
There was another patch to create/apply at install in order to make the `rake assets:precompile` work. I identified and confirmed the problem on the Discourse forum [here](https://meta.discourse.org/t/uglifier-error-during-assets-precompile/96970/4).
Please don't hesitate to have a look at it if you don't mind, as I don't see free time coming any time soon... 
:sweat:

**Comment by Josue-T** [comment]
Fixed by https://github.com/YunoHost-Apps/discourse_ynh/pull/8
